CC = g++
CFLAGS = -Wall -g

all: lab3.1

lab3.1: main.o
	$(CC) $(CFLAGS) main.o -o sorts

main.o: main.cpp array_sequence.hpp dynamic_array.hpp linked_list.hpp Sequence.hpp
	$(CC) -c main.cpp -o main.o
